### ISSUE TITLE
Scatter plot to show Time on X-axis and option to remove slider

### ISSUE THREAD

**Issue by xxeasterxx** [microsoft/tsiclient#106]
For scatter plot, the chart shows a slider at bottom of the chart which one need to slide it to show data points at that certain minute (e.g. bucketSize: 1 minute, i had to slide the slider to show data point at each minute). Is it a temporary solution? Isn't there a way to show all data points without the slider? More specifically, the spMeasures X-Axis should be the time.

**Comment by ccrowley96** [comment]
Hi!  Checkout [the scatter plot API reference](https://github.com/microsoft/tsiclient/blob/master/docs/UX.md#scatter-plot).  You can use the **isTemporal** chartOption to change the data display from time sliced with a slider to showing all timestamps at once.  The scatter plot must plot two values against one another however, with an optional parameter for radius of the points.

**Comment by xxeasterxx** [comment]
I have data which I just need to plot against Y-axis and X-axis being the time. Is it possible for the X-axis to be optional on this case? Is there any examples for scatter plot?

**Comment by ccrowley96** [comment]
If you're looking to plot data on the Y axis vs time, I'd recommend checking out the line chart!  The latest updates in scatter plot are not in NPM yet, but they'll be out soon.

**Comment by darsney** [comment]
Also, if you are really set on using the x axis for time, you can specify milliseconds of the time you intend to use as a value (using .valueOf()) and plot that on the x axis.  If you could share an example of a chart that uses scatterplot and x axis as time that would be cool, I'm curious in the use case

Alternatively you can enable dots and hide the paths of lines using CSS in the line chart, that should give you a similar effect

**Comment by xxeasterxx** [comment]
> If you're looking to plot data on the Y axis vs time, I'd recommend checking out the line chart! The latest updates in scatter plot are not in NPM yet, but they'll be out soon.

As the data points are quite densed, having line chart makes it look messy.
![image](https://user-images.githubusercontent.com/8415837/58999787-2a429c80-883a-11e9-9b5e-e3af549ac05c.png)


> Also, if you are really set on using the x axis for time, you can specify milliseconds of the time you intend to use as a value (using .valueOf()) and plot that on the x axis. If you could share an example of a chart that uses scatterplot and x axis as time that would be cool, I'm curious in the use case
> 
> Alternatively you can enable dots and hide the paths of lines using CSS in the line chart, that should give you a similar effect

Above image is a use case, I've 4 values I need to plot against time. If I used line chart and change the line colors to white, and enable the dots for all 4 values, they're all black and cannot customize the color, moreover the legend color too. So I hope that the scatter plot can have out of the box, just plot X-axis as the time.

**Comment by darsney** [comment]
Hi, here's a minimal example in a single file that does what you are trying to achieve...I'm going to go ahead and close this issue now.  Thanks for using the library!

https://codepen.io/anon/pen/xNvbBQ
