### ISSUE TITLE
No Context Menu on Heatmap

### ISSUE THREAD

**Issue by flowest** [Microsoft/tsiclient#12]
Although i configured the `aggregateExpression` to have one, there is no context menu shown on a heatmap.
LineChart works, but heatmap doesn't

```
let contextMenu = [{
   name: 'myAction',
   action: (aggregateExpression: any, splitBy: any, timeStamp: any) => {
                console.log('hello');
   }
}];

let ae = [];
ae.push(
   new TsiClient.ux.AggregateExpression(
      { predicateString: `myPredicate = \'${this.myPredicate}\'` },
      { property: myProperty, type: 'Double' },
      ['avg'],
      { from: this.myStartDate, to: this.myEndDate, bucketSize: '1s'},
       null,
      'red',
       'MyAlias',
       contextMenu));

// do the API stuff...

let heatMap = new TsiClient.ux.Heatmap(document.getElementById('heatmap'));
   heatMap.render(
   transformedResult,
   { theme: 'light' },
   ae);
```

Is this a bug?

**Comment by matdarMsft** [comment]
good point, context menu is not currently supported in heatmap since we haven't needed it for our purposes just yet.  i'd expect it to be added in the 2-6 month timeframe

we are also working on proper documentation of the APIs in the SDK so that you can know what is supported where, will keep you posted

**Comment by matdarMsft** [comment]
We have added some pretty extensive documentation, but we still don't support context menu for heatmap.  I'm going to close this issue for now, but will be sure to let you know when context menu is added.  Stay tuned!
