### ISSUE TITLE
Unhandled rejection TypeError: tsiClient.server.getEvents is not a function

### ISSUE THREAD

**Issue by neo-64** [microsoft/tsiclient#133]
Hi,

When i try tu use https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/time-series-insights/tutorial-create-tsi-sample-spa.md

the last exemple doesn't work 
```
 // Example 18 Events Table
        var startDate4 = new Date('2017-04-15T13:00:00Z');
        var endDate7 = new Date(startDate4.valueOf() + 1000*60*60*5);
        authContext.getTsiToken().then(function(token){
            tsiClient.server.getEvents(token, '10000000-0000-0000-0000-100000000108.env.timeseries.azure.com', 
                                        {predicateString: "Factory = 'Factory1'"},  {}, startDate4.valueOf(), 
                                       endDate7.valueOf()).then(function (events) {
                var transformedEvents = tsiClient.ux.transformTsxToEventsArray (events, {});
                var eventsTable = tsiClient.ux.EventsTable(document.getElementById('chart18'));
                eventsTable.render(transformedEvents, {theme: 'light'}, true);
            });
        });
```
tsiClient.server.getEvents is not a function i have the same issue with getTsqResults any idea ?

regards

**Comment by darsney** [comment]
This is likely an issue with your configuration.  Here is a working example of getEvents (drag a region in the chart, click 'explore events')
https://tsiclientsample.azurewebsites.net/withplatform/exploreevents.html

And here is working example of getTsqResults...
https://tsiclientsample.azurewebsites.net/withplatform/PAYG.html

If you can create and deploy a repro of your issue I would be willing to check it out
