### ISSUE TITLE
Integrated Charts Not Working

### ISSUE THREAD

**Issue by PatrickMcvay** [microsoft/tsiclient#135]
None of the integrated charts on the example site actually work. I am using edge to view them. The attached picture shows what I see when I go to https://tsiclientsample.azurewebsites.net/withplatform/PAYG.html
![Annotation 2019-08-16 102441](https://user-images.githubusercontent.com/19638117/63178652-16709f00-c010-11e9-83b1-f41ab30d06df.png)

**Comment by darsney** [comment]
Ahh yes, this is because we were using the object spread operator in boilerplate/auth.js which is [not supported in Edge](https://github.com/Microsoft/ChakraCore/issues/3406)

I have resolved the issue by removing the spread operator.  Do a hard refresh and the page should work in Edge now
