### ISSUE TITLE
Preview version of TSI with deep nesting & aggregation. 

### ISSUE THREAD

**Issue by shmisra** [microsoft/tsiclient#136]
As per best practices: Don't use deep array nesting. Time Series Insights supports up to two levels of nested arrays that contain objects. Time Series Insights flattens arrays in the messages into multiple events with property value pairs.
For TSI in preview. 
A.	Does the preview version support deep array nesting? 
B.	If Yes, Does the preview version support aggregate query?

**Comment by darsney** [comment]
This is a question related to your specific IoT architecture and not the Time Series Insights JavaScript SDK.  This has nothing to do with the SDK, and is an inappropriate use of Issues.  Do not open issues of this nature against the SDK. Closing

As an attempt to address your question: 
Per best practices, message properties should be flat for aggregation is S SKUs.  In preview (PAYG) SKUs, time series models support displaying instances in a hierarchy, but rolling up multiple instances into a single aggregate is not presently supported...you can only view a single variable per instance at a time.  You should not nest your properties if possible, and should use an S SKU to aggregate multiple sensors
