### ISSUE TITLE
Skip step :Authentication and authorization to create an application

### ISSUE THREAD

**Issue by BhupalPatil** [microsoft/tsiclient#150]
Hi Team, I'm working on UI application that pulls data from Azure TSI and build charts using TSI JS SDK. I'm trying to us the TSI JS SDK however it needs the client ID generated by registering the application to azure AD account.  IS it possible to access TSI data and build chart without registering the application on Azure AD and access the data by some other way?

Thanks,
Bhupal

**Comment by darsney** [comment]
You will need to register the application in Azure AD to get access tokens to query the TSI API directly from the browser. You could also create your own server side and issue queries to the TSI API from there, then use the SDK in browser to visualize the results.  

Regardless, this is not an issue in the SDK and does not generally pertain to tsiclient.  This is more of a question of application architecture on top of the Microsoft AD stack, so I am closing this issue
