### ISSUE TITLE
Time Series Insights C# SDK

### ISSUE THREAD

**Issue by wangkanai** [microsoft/tsiclient#174]
When would you release a Time Series Insights C#.NET SDK on .NET Standard 2.0? or is there any plans at all?

**Comment by xtellurian** [comment]
I'm also interested in a C# SDK. I've published a basic NuGet package with the sample C# client.

It's unsupported, use at your own risk, but it mostly works.

https://www.nuget.org/packages/AmphoraData.TSI.CSharp/

**Comment by darsney** [comment]
There is a C# client that can be used with the PAYG SKU (currently in Preview).  It lives here...

https://github.com/Azure-Samples/Azure-Time-Series-Insights/tree/master/csharp-tsi-preview-sample

Will keep you posted about future releases of the SDK as we announce them!
