### ISSUE TITLE
Authentication problem with tsiclient samples

### ISSUE THREAD

**Issue by GSpaces-Admin** [microsoft/tsiclient#179]
I cannot log in to any of the samples that include authentication.  I have been able to do so in the past.  I have tried several different accounts of different types and even browsers and machines.  Am I doing something daft or has it been broken during recent updates?

**Comment by darsney** [comment]
That is really strange!  Are you using an account associated with Azure Active Directory?  Microsoft accounts (like your personal outlook.com account, for example) will not work with third party apps on top of Time Series Insights.  Unfortunately I can't reproduce this issue, is there a specific error you are seeing?

**Comment by darsney** [comment]
closing this issue since it is now stale
