### ISSUE TITLE
Expose types

### ISSUE THREAD

**Issue by jb-reefer** [microsoft/tsiclient#187]
Howdy! Seeing as you folks have a ton of TypeScript in this repo, have you thought about shipping the types? It'd make life a lot easier!

**Comment by darsney** [comment]
Oh man this is a stellar idea and seems pretty easy to do!  Probably should have done this a while ago to be honest, I typo myself all over the place when I consume the library and I own the damn thing haha! 

Let me experiment with consuming a d.ts file myself today and i'll point you to a beta release on NPM so we can get feedback, thanks!

**Comment by darsney** [comment]
So we took a look at this and have a [PR up](https://github.com/microsoft/tsiclient/pull/199), but we are gonna hold out and take a look at it next week before merging.  I dropped the built library and typings into an app, and we get good type resolution for methods directly on TsiClient.ux and TsiClient.server, but getting typings for viz components has been a bit cumbersome, as in this example...

`let lineChart = new tsiClient.ux.LineChart(el);  // plays well with typings`
`lineChart.render(...) // lineChart will generally have type "any" so plays badly with typings`

I'd like to get a clean typings bundle that plays nicely in vscode automagically, and as a side effect it would be really nice to also get proper module loading so you can do something like...

`import {LineChart} from "tsiclient"`
`let lineChart = new LineChart(el)`

I want to make sure we do this right so we don't end up creating a breaking pattern for TS developers once we add typings and proper modules, it's just gonna be a bit more of a time investment to make sure we also don't break the vanilla JS render pattern.  

Will keep you posted, feel free to comment with any feedback you have on the approach.  Thanks!

**Comment by xtellurian** [comment]
@darsney I just took a look at this branch, and the typings work OK for me

<img width="487" alt="image" src="https://user-images.githubusercontent.com/8497130/91383095-a88bc400-e86e-11ea-9979-9b8f94fc36e3.png">

Can we merge this PR, publish the types, and at least see how that works downstream? I can try the new version with types ASAP.

**Comment by darsney** [comment]
We just published a beta with types and modules!!!

Just run "npm install tsiclient@beta" to try it out. 

The branch for these changes is here...
https://github.com/microsoft/tsiclient/tree/user/cocrowle/optimize-rollup

npm package is here...
https://www.npmjs.com/package/tsiclient/v/1.4.0-beta.0

Usage is hopefully how you'd expect...
![image](https://user-images.githubusercontent.com/4854357/94071373-a1da6900-fda8-11ea-89cd-73dfd7bb2e63.png)

Please let us know if you hit issues, this should roll out as 1.4.0 this week!

**Comment by darsney** [comment]
We just published a beta with types and modules! This should tree-shake and ensure your bundle size isn't exploded if you don't use all the components. The package dependencies are also appropriately handled to ensure you don't double load things like the Azure Maps SDK or D3 if you already use them

Just run `npm install tsiclient@beta` to try it out.

The branch for these changes is here...
https://github.com/microsoft/tsiclient/tree/user/cocrowle/optimize-rollup
#271 

npm package is here...
https://www.npmjs.com/package/tsiclient/v/1.4.0-beta.0

Usage is hopefully how you'd expect...
![image](https://user-images.githubusercontent.com/4854357/94082580-123bb700-fdb6-11ea-8bc6-4ab23bfc5d0e.png)

Please let us know if you hit issues, this should roll out as 1.4.0 this week!
