### ISSUE TITLE
Ellipsis Option "Display Grid" should be "Display Table"

### ISSUE THREAD

**Issue by xtellurian** [microsoft/tsiclient#189]
The ellipsis option "Display Grid" implies to users that **grid lines** will be overlay on top of the graph. 

However that is not what happens. 

What actually happens is a table is displayed with the associated data. 

There are two options:

* Change the name of the option to "Display Table" (my suggestion)
* Actually display a grid and not a table

**Comment by xtellurian** [comment]
This might be very easily fixed by changed the value in `Strings.ts`

... although that might not be the purpose of that file. I'm happy to do a PR, but I want some pointers on where to make change.

**Comment by darsney** [comment]
Great point!  I agree that the content is misleading there, will consider a change

For your purposes, you might also be pleased to know that you can modify strings using the "strings" chart option, which is really handy for localization too!  

Check out [this example](https://codepen.io/darsney/pen/OKZRgP).  Overriding strings is something we are really stoked about, but still testing, hence it being undocumented right now.  We use it in production for localization, so we are pretty sure its good to go as a concept and the usage is what we want it to look like, we just don't want to publish it until we are sure its supported all over

For now you can pass in strings as a chart option, where its value is an object, with keys as defined in Strings.ts, and values defined as whatever you want.  Hopefully the usage is clear from the example 

Feel free to let us know how its working out for you!

**Comment by xtellurian** [comment]
Thanks @darsney that is super useful!
