### ISSUE TITLE
Outdated dependencies / vulnerabilities

### ISSUE THREAD

**Issue by MariuszKogut** [microsoft/tsiclient#195]
I'm evaluating Azure TimeSeries right now as a solution for our tenant based IoT product. It's great to have a JS library, where I can create our dashboards on the fly in our SPA. I have checked the package.json and found a lot of outdated dependencies:

``npx npm-upgrade``:

```
New versions of active modules available:

  array-includes              ^3.0.3   →    ^3.1.1
  awesomplete                 ^1.1.2   →    ^1.1.5
  @types/awesomplete          ^1.1.8   →   ^1.1.10
  d3                         ^4.13.0   →   ^5.15.0
  @types/d3                  ^4.13.0   →    ^5.7.2
  d3-interpolate-path         ^1.1.1   →    ^2.1.1
  moment-timezone            ^0.5.21   →   ^0.5.27
  npm                         ^6.4.0   →   ^6.13.7
  promise-polyfill            ^7.1.0   →    ^8.1.3
  css-loader                ^0.28.11   →    ^3.4.2
  file-loader                ^1.1.11   →    ^5.0.2
  mini-css-extract-plugin     ^0.4.4   →    ^0.9.0
  node-sass                   ^4.9.3   →   ^4.13.1
  sass-loader                 ^6.0.7   →    ^8.0.2
  style-loader               ^0.19.1   →    ^1.1.3
  ts-loader                   ^5.2.2   →    ^6.2.1
  typescript                  ^3.7.2   →    ^3.7.5
  url-loader                  ^1.1.0   →    ^3.0.0
  webpack                    ^4.20.2   →   ^4.41.5
  webpack-cli                 ^3.1.2   →   ^3.3.10
  webpack-dev-server          ^3.1.9   →   ^3.10.3`
```

Also there are some vulnerabilities (run ``npm audit`` to see more details):

```
found 37 vulnerabilities (12 low, 2 moderate, 23 high) in 16153 scanned packages
```

Are there any plans to update this project?

**Comment by darsney** [comment]
I've gone ahead and fixed the vulnerabilities from npm audit as part of [this commit](https://github.com/microsoft/tsiclient/commit/454f027966ee12809a371e195cc5678c33dc7d04). Those will go out with the next version of the SDK (1.3.6, currently in [beta](https://www.npmjs.com/package/tsiclient/v/1.3.6-beta.3)).  

I'm gonna hold off on upgrading the outdated dependencies unless there is a compelling reason to upgrade any of them.  I'm open to a discussion on which ones to upgrade and why if you feel strongly about it.

Thanks for bringing this up, I'd been meaning to get around to it!

**Comment by darsney** [comment]
Closing this issue as we have updated the necessary packages via npm audit fix and there is no new conversation
