### ISSUE TITLE
Examples for loading a TSI payload from a 3rd party API

### ISSUE THREAD

**Issue by alexmarshall132** [microsoft/tsiclient#213]
I'm currently using TSI within Azure and want to use it as the backing store for my customers' device data. However, due to the security model of TSI, I can't expose it directly to my customers, so I'd like to expose TSI payloads through my own API. It appears that this should be possible based on the way the tsiclient SDK is structured. Can we get some examples of how to load a serialized JSON QueryResultPage object into a Line Chart (or other visuals) without using tsiClient.server ?

**Comment by darsney** [comment]
Totally!  We have a lot of folks who will use their own backend to issue calls directly to the TSI API, using their own access control and a service principal to authenticate with the API.  

Those results can then be passed directly to the browser the same way you receive them from the TSI API, and you can use the methods for transformation to render them in the chart as if they came directly from the TSI API using CORS

**Comment by alexmarshall132** [comment]
> Can we get some examples of how to load a serialized JSON QueryResultPage object into a Line Chart (or other visuals) without using tsiClient.server ?

Closed without the requested examples ?
