### ISSUE TITLE
Browser support of the charting components

### ISSUE THREAD

**Issue by nbevans** [microsoft/tsiclient#216]
We're evaluating whether to use tsiclient as a basis for a cross-platform charting component. The idea would be cover web and Android/iOS/UWP mobile platforms (via "web view" obviously).

My question is whether the charting components are built with certain browser version support in mind?

**Comment by darsney** [comment]
This is a great question, the components should work well in all modern web browsers...meaning everything but IE (e.g. Chrome, FF, Edge) 

I believe that mobile implementations of chrome and safari should work quite well, and I'm guessing that UWP Edge implementations should be fine as well, and probably even more fine if UWP moves towards chromium based Edge

Touch support is probably lacking, and you would likely benefit from using a different library if touch scenarios are very important to you.  We don't have much need for touch right now for our use cases unfortunately, so the library is not optimized for them
