### ISSUE TITLE
The bundle size is large

### ISSUE THREAD

**Issue by xtellurian** [microsoft/tsiclient#265]
Is there a way we can reduce the size on disk of tsiclient?

Indicators that the size is large include:

* tsiclient on [npm](https://www.npmjs.com/package/tsiclient) is ~9MB
* tsiclient is 30% of my app's bundle 

Options we could explore are:
* optimization in the webpack build to reduce size of the /dist/ dir
* removing some dependencies

**Comment by darsney** [comment]
yeahhh tsiclient is def getting massive now, i hear ya.  makes me sad too because i hate taking dependencies on giant libraries, and now i work on one haha! 

probably only getting bigger since we added a reference to the azure maps SDK as well for a new component.  we do have some plans to improve support for typings, module loading etc etc, we can take a swing at reducing the size of the library as well as part of that.  

open to any ideas for low hanging fruit that you have as well, apologies!

**Comment by darsney** [comment]
i got @ccrowley96 taking a look.  for context, [highcharts ](https://www.npmjs.com/package/highcharts)is 43MB, but probably has better module loading/tree shaking fanciness that means it doesnt all go in your bundle, we gotta think about how to do that, but i know its what the people probably want

**Comment by xtellurian** [comment]
Running `webpack-bundle-analyzer` on /dist/ produces these warnings:

```
    "configuration\nThe 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.\nYou can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/",
    "asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).\nThis can impact web performance.\nAssets: \n  tsiclient.css (560 KiB)\n  tsiclient.js (2.16 MiB)",
    "entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.\nEntrypoints:\n  main (2.71 MiB)\n      tsiclient.css\n      tsiclient.js\n",
    "webpack performance recommendations: \nYou can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.\nFor more info visit https://webpack.js.org/guides/code-splitting/"
```

I also used [Bundle Phobia](https://bundlephobia.com) to compare highcharts to tsiclient, and tsiclient is actually significantly larger (~260kB, ~2.2mB)

**Comment by xtellurian** [comment]
a small PR to add bundle analyser so we have at least 1 common method of looking at the size

https://github.com/microsoft/tsiclient/pull/268

**Comment by darsney** [comment]
touche, shows that i have no idea what the difference between "unpacked size" and "amount that this increases the size of my bundle" is.  clearly a blind spot for me and this package right now haha!

appreciate you checking this out and keepin us honest here!  will check out the PR

**Comment by xtellurian** [comment]
@darsney I'm on a real-life crash course learning how bundle size affects load time and build time!

webpack does magic and I'm scared to look inside the black box 🤯

**Comment by ccrowley96** [comment]
@xtellurian thanks for the feedback.  I'll be looking into this over the next couple of days.

I checked out the BundleAnalyzerPlugin you referenced in your PR.  Pretty cool stuff.  Here's the output.  It looks like the maps dependency is pretty heavy.  Stay tuned.
![image](https://user-images.githubusercontent.com/18181049/91109246-42652e00-e62f-11ea-854e-2b2adba505ef.png)

**Comment by ccrowley96** [comment]
@xtellurian Checkout the [rollup branch](https://github.com/microsoft/tsiclient/tree/user/cocrowle/optimize-rollup).

I set up a new build system which does the following:

1. Generates **tsiclient.umd.js** bundle for commonjs / browser script tag consumption
2. Generates **components.js** bundle targeting es modules to allow: `import { LineChart } from 'tsiclient/components'`
3. Generates **tsiclient.js** bundle targeting es modules to support current import syntax: `import TsiClient from 'tsiclient'` (imports all of tsiclient)

We're still working on testing this, but the module bundling seems to be working.  I set up a create-react-app to test the library.  The bundles work, but I didn't see any file size reduction via tree shaking.  Looking into that now.  Ideally, applications that consume this library, using webpack / rollup, would be able to tree shake dependencies and use only what was imported.

If that doesn't work, I'll look into separating everything depending on azure-maps-control into a different entry point.

**Comment by xtellurian** [comment]
@ccrowley96 looking pretty good! I haven't used rollup before, but it seems like a good solution.

2 questions:

1) There's a commit in there about dynamic loading atlas, but I don't see it in the PR... what's going on there? I know the atlas lib also has some weird module loading-ness

2) Could you publish this as a pre-release version to npm so I can test it?

**Comment by ccrowley96** [comment]
The dynamic loading commit was an attempt to asynchronously load atlas only if a component depending on it was called.  It's a cool technique, but what webpack calls 'dynamic code splitting' is meant for applications not libraries.  It runs into problems if the library code is bundled again by the application consuming it.

We're not ready to publish yet, but you're welcome to test a local npm build in your app.

To build:

1.  Check out the user/cocrowle/optimize-rollup branch
2. `npm run build`
3. `npm run pack`
4.  Copy the file path to the tarball generated in dist/tsiclient.tar.gz
5. `npm install [paste path here]` in your test application directory
6. `import { LineChart } from 'tsiclient/components'` should now work

`pack` is a cool command I found recently that will create a local version of what npm publishes (perfect for testing)

Let me know if you have any questions!

**Comment by darsney** [comment]
We just published a beta with types and modules!!!  This should tree-shake and ensure your bundle size isn't exploded if you don't use all the components.  The package dependencies are also appropriately handled to ensure you don't double load things like the Azure Maps SDK or D3 if you already use them

Just run "npm install tsiclient@beta" to try it out. 

The branch for these changes is here...
https://github.com/microsoft/tsiclient/tree/user/cocrowle/optimize-rollup

npm package is here...
https://www.npmjs.com/package/tsiclient/v/1.4.0-beta.0

Usage is hopefully how you'd expect...
![image](https://user-images.githubusercontent.com/4854357/94071373-a1da6900-fda8-11ea-89cd-73dfd7bb2e63.png)

Please let us know if you hit issues, this should roll out as 1.4.0 this week!

**Comment by darsney** [comment]
We just published a beta with types and modules! This should tree-shake and ensure your bundle size isn't exploded if you don't use all the components. The package dependencies are also appropriately handled to ensure you don't double load things like the Azure Maps SDK or D3 if you already use them

Just run `npm install tsiclient@beta` to try it out.

The branch for these changes is here...
https://github.com/microsoft/tsiclient/tree/user/cocrowle/optimize-rollup
#271 

npm package is here...
https://www.npmjs.com/package/tsiclient/v/1.4.0-beta.0

Usage is hopefully how you'd expect...
![image](https://user-images.githubusercontent.com/4854357/94082580-123bb700-fdb6-11ea-8bc6-4ab23bfc5d0e.png)

Please let us know if you hit issues, this should roll out as 1.4.0 this week!
