### ISSUE TITLE
TSI charts mess up the dates during month end

### ISSUE THREAD

**Issue by skhye05** [microsoft/tsiclient#278]
Hi, 

I am currently using the TSI Chart to plot some data, and set the range date to picked up the data for instance for 2 days. but every month end the data isn't showing.

![image](https://user-images.githubusercontent.com/11404583/94915929-02a32900-04ae-11eb-9dd6-647f902af8e7.png)

The issue seems to be on the date time manipulation where the range is set between the last day of the month and the begin of the new month i.e. june 30 - 1 july.

Can you please help?

Thanks

**Comment by darsney** [comment]
If you could create a codepen that minimally reproduces this issue, we can take a look.  I have not seen any issue like this in our usage of the components, so I'm guessing it is related to the way you are consuming the component, or the shape of your data...not the library.  Happy to help, just need to see what you're doing

**Comment by darsney** [comment]
Closing this issue as stale, feel free to reopen if you have a stable repro via Codepen
