### ISSUE TITLE
Render only linechart, retrieved from backend API

### ISSUE THREAD

**Issue by lindsve** [microsoft/tsiclient#287]
Hi,

We are developing a dashboard which is fed events using EventHub. The dashboard is compromised of a table where the rows represent wells and each column represents different algorithms running on live data from these wells. Each cell is as such a representation of the given algorithm state on that particular well.

We are looking for a way to add a "sparkline" which displays the historical (a few hours) state of that cell, and I have looked at using TimeSeries Insight for this. I have played around a little bit in the TSI Explorer and so far it looks feasible.

Is there a way to use this client to render *only* the linechart like the following (no legend, no axis labels)?
![Skjermbilde 2020-11-05 kl  12 33 43](https://user-images.githubusercontent.com/159861/98236229-4e406b00-1f63-11eb-93c7-b520c61ac103.png)

I have managed to replicate the query which I created in TSI Explorer on our backend and can get the data, but that is as far as I have managed to get. If I return the data back to our frontend application then it is in the wrong format for the chart component. I've tried to figure out how to use the `tsiClient.ux.transformAggregatesForVisualization()` function, but I'm a bit lost on the part with the options for that function.

Any guidance on what options to use to get the above linechart? The data is categorical, btw.

**Comment by darsney** [comment]
Cool use case!  You should try hiding all the elements you don't want using CSS.  We deliberately use classnames of the format ".tsi-" to allow you to do customizations of this nature

Here is an example of how to do this in a grid...
https://codepen.io/darsney/pen/VwjBJeY

To transform your data for a Gen2 SKU you are going to want to use this function actually...
```tsiClient.ux.transformTsqResultsForVisualization```

See example usage here...
https://github.com/microsoft/tsiclient/blob/master/pages/examples/withplatform/PAYG.html#L67

**Comment by lindsve** [comment]
Thanks, hiding using CSS seems to do the trick, although I'm struggling a little bit with sizing/placing the rendered svg plot. 

Getting closer though 👍

**Comment by darsney** [comment]
Closing this issue since you got it working, thanks!
