### ISSUE TITLE
Units in LineChart (BarChart)

### ISSUE THREAD

**Issue by MartinMilata** [microsoft/tsiclient#318]
Is there any possibility to show units (meters, secundes, wats, and so on ) in graph Y-axis? 
I would like to show information, that first graph is forexample in A-unit, and the second in B-unit. 
![image](https://user-images.githubusercontent.com/79250857/115703319-47b77b80-a36a-11eb-8a0c-9cf7c031102b.png)

**Comment by ccrowley96** [comment]
Hi @MartinMilata, please take a look at this hosted example: https://tsiclientsample.azurewebsites.net/noauth/swimlaneOptions.html.

This is the code for that sample which shows how to add labels to each Y-Axis via the `swimLaneOptions` chart option.
https://github.com/microsoft/tsiclient/blob/8b40d158139e77b4eb9bc10dfa76944fccde5cf8/pages/examples/noauth/swimlaneOptions.html#L62

Using `swimLaneOptions`, you'll be able to add labels for each line!
Here is the interface for that option:
```ts
public swimLaneOptions: {[key: number]: swimLaneOption} | null;

interface swimLaneOption {
    yAxisType: YAxisStates, 
    label?: string, 
    onClick?: (lane: number) => any, 
    collapseEvents?: string
}
```
