### ISSUE TITLE
Authentication failed on calling tsiClient.server.getAggregates()

### ISSUE THREAD

**Issue by karthik282** [microsoft/tsiclient#333]
@darsney  
I am using MSAL for authentication in my react project. After we login with my AAD id will get a token and stored in cookies,

Now for time series I have made called a function tsiClient.server.getAggregates(token,FQDN,array)
token -> token is passed from stored cookie with Bearer i am passing token value.
FQDN -> tsi environment set 
array -> custom array

Error I am getting is Post call 401 Authorization error 
![tempsnip](https://user-images.githubusercontent.com/89376253/131349159-378cda28-a32c-4f00-9fc2-e6b66b0c2e48.png)

**Comment by darsney** [comment]
if the token is actually an ID token and not an access token for the Time Series Insights API scope, it will not work.  if you could check out what the scope of your token is, that may explain the issue
