### ISSUE TITLE
Time comes in UTC format by default in linehcart

### ISSUE THREAD

**Issue by prabgupta** [Microsoft/tsiclient#58]
The time always comes in UTC format, no matter what value we send.

**Comment by matdarMsft** [comment]
Apologies for the delayed response...

Adding an “offset” value to the chart options (second parameter in any of the chart’s render functions), will shift the time from UTC. If offset isn’t provided, the default is to use UTC time.

Here’s an example render function call for a line chart using an offset of -60 minutes: (13:00 in UTC will be displayed now as 12:00)
```javascript
lineChart.render(transformedResult, {theme: 'light', grid: true, offset: -60}, aggregateExpressions2);
```

Here’s an example render function call for a line chart using the America/Los Angeles timezone: (13:00 in UTC will be displayed now as 6:00)
```javascript
lineChart.render(transformedResult, {theme: 'light', grid: true, offset: “America/Los_Angeles”}, aggregateExpressions2);
```

And finally here’s an example using local time:
```javascript
lineChart.render(transformedResult, {theme: 'light', grid: true, offset: “Local”}, aggregateExpressions2);
```

**Comment by prabgupta** [comment]
Thanks
