### ISSUE TITLE
Need to set Y axis scale manually

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [Microsoft/tsiclient#62]
We need to set the Y axis scales manually rather than use the auto-scale, which magnifies small variations all out of proportion. I can find nothing in the scant docs about this.

We have a trade show this Tuesday, Feb 5 and would greatly appreciate an answer on Monday Feb 4 if at all possible.

**Comment by sergaz-msft** [comment]
@niusoff can you take a look at this issue? Thank you so much.

**Comment by matdarMsft** [comment]
apologies for the delayed response...setting y axes manually is not presently possible, but will likely be supported in an upcoming release.  this is a known request from users of both the SDK and of Azure TSI in general.  

regarding documentation, i'm actually working on a huge documentation overhaul, stay tuned for a merge of [the docs branch](https://github.com/Microsoft/tsiclient/tree/docs) around the end of february, along with an improved examples page.  thanks for the feedback roy!

**Comment by matdarMsft** [comment]
Aside, @JetstreamRoySprowl, how would you prefer that overflowing lines are handled in the event that y axes are stacked, but a manual scale is used?  Would you prefer that lines flow outside of their "swim lane" or that they are clipped when they overflow outside?  Most industrial process visualizations allow overflow of lines on top of each other and require users to manipulate the y axis to fix it if they wish, just wanted to clarify that this is the expectation

**Comment by matdarMsft** [comment]
This is now supported via the yExtent chartOption and chartDataOption, see example usage [here](https://github.com/Microsoft/tsiclient/blob/cec9c25d40d3f4e348be0816ba4c8ed758fab729/pages/samples/examples/noauth/basiccharts.html#L38)
