### ISSUE TITLE
head.js wait for window.onload

### ISSUE THREAD

**Issue by rbrundritt** [microsoft/tsiclient#75]
If you put the head.js script tag in the head of the page, for many it will throw an error on page load as it tries to access the body of the page before it is loaded. Consider wait until for the window.onload event before accessing the body of the page.

**Comment by KingdomOfEnds** [comment]
If I can chime in here - the hosted samples are great: https://tsiclientsample.azurewebsites.net/ but they don't mirror some of the samples in the `master` branch. For example, some of the dependencies are missing, some of the link elements have closing tags (they shouldn't), etc. You can copy the entire code snippet, say here: https://tsiclientsample.azurewebsites.net/noauth/multipleseriestypes.html by **right-clicking and selecting web-inspector > inspect element > copy (the entire html by right-clicking on it and selecting copy).** Is that something we want to update? I'm currently working on

**Comment by matdarMsft** [comment]
I've refactored to add head.js to the top of the files, which is in line with standard js linking conventions.  I agree that it is somewhat suboptimal that head.js is required to run the samples locally, but it is appropriately commented in the source code, and the significant benefit to development by having the headers dynamically injected in each individual sample is worth the slight indirection
