### ISSUE TITLE
Supporting TSI preview version?

### ISSUE THREAD

**Issue by Quentinvk** [microsoft/tsiclient#88]
Is the TSIclient working with the preview version of TSI? 

If it does, a little help would be most welcome.
I'm using MVC and making the calls on the server side, but I don't understand how I should make the call with aggregateExpression.toTsx() as body. And what would the result look like? 
Thank you 
Quentin

**Comment by matdarMsft** [comment]
Hi Quentin,
Apologies for the delayed response!  [Here ](https://tsiclientsample.azurewebsites.net/withplatform/PAYG.html)is an example of using TSIclient on a PAYG SKU

The example is in the browser using CORS...if you are making the calls on the server side, you could use a similar pattern in node, or refer to the API for aggregate series [here](https://docs.microsoft.com/en-us/rest/api/time-series-insights/preview-query#aggregate-series-api)

Please let me know if you have other questions...thanks!

-Matt
