### ISSUE TITLE
Authenticate with msal.js

### ISSUE THREAD

**Issue by flowest** [Microsoft/tsiclient#9]
I did the [example](https://docs.microsoft.com/de-de/azure/time-series-insights/tutorial-explore-js-client-lib) with tsiclient.js and everything worked fine.

My question now is: how can i authenticate with another js-library, in my case msal.js? Where do i get the token from?
(not sure if this is a msal.js or a tsiclient.js question)

**Comment by matdarMsft** [comment]
probably more of an msal.js question...check out the code here to see an example using msal.js

https://github.com/Microsoft/tsiclient/blob/msalIntegration/pages/samples/msal.html

I have a reliable repro of an issue im hitting in the library, but moving forward i think msal.js will be the right choice for SPAs integrating with AAD
